<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.SDK" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Deckwraith.Application/Deckwraith.Application.csproj" />
    <ProjectReference Include="../Deckwraith.Core/Deckwraith.Core.csproj" />
    <ProjectReference Include="../Deckwraith.Mcp/Deckwraith.Mcp.csproj" />
  </ItemGroup>
</Project>
