<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.SDK" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Deckwraith.Application/Deckwraith.Application.csproj" />
    <ProjectReference Include="../Deckwraith.Continuity/Deckwraith.Continuity.csproj" />
    <ProjectReference Include="../Deckwraith.Kernels.CSharp/Deckwraith.Kernels.CSharp.csproj" />
    <ProjectReference Include="../Deckwraith.Kernels.PowerShell/Deckwraith.Kernels.PowerShell.csproj" />
    <ProjectReference Include="../Deckwraith.Mcp/Deckwraith.Mcp.csproj" />
    <ProjectReference Include="../Deckwraith.Notebooks/Deckwraith.Notebooks.csproj" />
    <ProjectReference Include="../Deckwraith.Persistence/Deckwraith.Persistence.csproj" />
    <ProjectReference Include="../Deckwraith.PowerShell/Deckwraith.PowerShell.csproj" />
    <ProjectReference Include="../Deckwraith.Providers.Anthropic/Deckwraith.Providers.Anthropic.csproj" />
    <ProjectReference Include="../Deckwraith.Providers.Google/Deckwraith.Providers.Google.csproj" />
    <ProjectReference Include="../Deckwraith.Providers.OpenAI/Deckwraith.Providers.OpenAI.csproj" />
    <ProjectReference Include="../Deckwraith.Providers.OpenAICompatible/Deckwraith.Providers.OpenAICompatible.csproj" />
  </ItemGroup>
</Project>
